# Generated by Django 3.2.13 on 2022-07-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmerblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='blog-post', max_length=255, unique=True),
        ),
    ]
