# Generated by Django 3.2.13 on 2022-07-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmerblog', '0007_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default='Delete and add your body content'),
        ),
    ]
